# blank_lines_upper_bound = 2
# control_brace_style = "ClosingNextLine"
# enum_discrim_align_threshold = 32
# fn_single_line = true
# format_code_in_doc_comments = true
reorder_imports = true
# group_imports = "StdExternalCrate"
# imports_layout = "Vertical"
# imports_granularity = "One"
